### ISSUE TITLE
AI Poptab Amount

### ISSUE THREAD

**Issue by wetnreckless** [Porkeld/A3xai-2.3#1]
Was wondering where you change the amount of Poptabs on the AI. I have read through the config.cpp in the a3xai_config.pbo and have not seen a setting to change the amount. However, I could just be blind.

**Comment by TheGrayJacket** [comment]
a3xai\compile\A3XAI_unit_spawning\A3XAI_createUnit.sqf

Edit this part:

private _AIMoney = 150 + (round (random 100));
_unit setVariable
[
    "ExileMoney",
    _AIMoney,
    true
];
